- hosts: all
  
  tasks:
   
   - name: Generate hosts file
     lineinfile: dest=/etc/hosts
                 regexp='.*{{ item }}$'
                 line="{{ hostvars[item].ansible_default_ipv4.address }} {{item}}"
                 state=present            
     when: hostvars[item].ansible_default_ipv4.address is defined
     with_items: "{{groups['all']}}"
     become: true
     
   - name: Set hostname
     hostname: name="{{inventory_hostname}}"
     become: true

   - name: apt update
     apt: update_cache=yes upgrade=dist
     become: true
     async: 300
     poll: 5 

   - name: Download git repository
     become: true
     git:
      repo: 'https://github.com/SNICScienceCloud/technical-training.git'
      dest: /technical-training 
      
   - name: Change ownership of a directory
     become: true
     file:
      path: /technical-training
      state: directory
      recurse: yes
      owner: appuser
      group: appuser

- hosts: prod_server
 
  vars_files:
   - setup_var.yml  
  
  tasks:  
   - name: Extra packages
     apt: pkg={{item}} state=latest update_cache=true 
     with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
     become: true  

   - name: apt update
     apt: update_cache=yes upgrade=dist
     become: true

   - name: Add Docker repository key
     apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
     become: true

   - name: Add Docker repository 
     command: add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
     become: true

   - name: apt update
     apt: update_cache=yes upgrade=dist
     become: true

   - name: Install Docker  
     apt: pkg=docker-ce state=present update_cache=true allow_unauthenticated=yes
     become: true

   - name: Download docker-compose 
     become: yes
     get_url:        
      url: "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-{{ansible_system}}-{{ansible_architecture}}"
      dest: /usr/local/bin/docker-compose
      mode: +x  

   - name: Building container
     become: true
     shell: docker build .
     args: 
      chdir: /technical-training/model-serving/ci_cd/production_server
     async: 300
     poll: 5

   - name: Running containers
     become: true
     shell: docker-compose up -d 
     args: 
      chdir: /technical-training/model-serving/ci_cd/production_server 
     async: 300
     poll: 5

- hosts: dev_server
  
  vars_files:
   - setup_var.yml

  tasks:
   - name: Extra packages
     apt: pkg=python3-pip state=latest update_cache=true  
     become: true

   - name: Install ML packages
     become: true
     pip: 
      name: keras, tensorflow, numpy
     async: 300
     poll: 5 
